using System.Drawing;

namespace Spiff.Core.API.Helpers
{
    public static class Colors
    {
        public static string Indigo = "4b0082";
        public static string Gold = "ffd700";
        public static string Hotpink = "ff69b4";
        public static string Firebrick = "b22222";
        public static string Indianred = "cd5c5c";
        public static string Yellow = "ffff00";
        public static string Mistyrose = "ffe4e1";
        public static string Darkolivegreen = "556b2f";
        public static string Olive = "808000";
        public static string Darkseagreen = "8fbc8f";
        public static string Pink = "ffc0cb";
        public static string Tomato = "ff6347";
        public static string Lightcoral = "f08080";
        public static string Orangered = "ff4500";
        public static string Navajowhite = "ffdead";
        public static string Lime = "00ff00";
        public static string Palegreen = "98fb98";
        public static string Greenyellow = "adff2f";
        public static string Burlywood = "deb887";
        public static string Seashell = "fff5ee";
        public static string Mediumspringgreen = "00fa9a";
        public static string Fuchsia = "ff00ff";
        public static string Papayawhip = "ffefd5";
        public static string Blanchedalmond = "ffebcd";
        public static string Chartreuse = "7fff00";
        public static string Dimgray = "696969";
        public static string Black = "000000";
        public static string Peachpuff = "ffdab9";
        public static string Springgreen = "00ff7f";
        public static string Aquamarine = "7fffd4";
        public static string White = "ffffff";
        public static string Orange = "ffa500";
        public static string Lightsalmon = "ffa07a";
        public static string Darkslategray = "2f4f4f";
        public static string Brown = "a52a2a";
        public static string Ivory = "fffff0";
        public static string Dodgerblue = "1e90ff";
        public static string Peru = "cd853f";
        public static string Lawngreen = "7cfc00";
        public static string Chocolate = "d2691e";
        public static string Crimson = "dc143c";
        public static string Forestgreen = "228b22";
        public static string Slateblue = "6a5acd";
        public static string Lightseagreen = "20b2aa";
        public static string Cyan = "00ffff";
        public static string Mintcream = "f5fffa";
        public static string Silver = "c0c0c0";
        public static string Antiquewhite = "faebd7";
        public static string Mediumorchid = "ba55d3";
        public static string Skyblue = "87ceeb";
        public static string Gray = "808080";
        public static string Darkturquoise = "00ced1";
        public static string Goldenrod = "daa520";
        public static string Darkgreen = "006400";
        public static string Floralwhite = "fffaf0";
        public static string Darkviolet = "9400d3";
        public static string Darkgray = "a9a9a9";
        public static string Moccasin = "ffe4b5";
        public static string Saddlebrown = "8b4513";
        public static string Darkslateblue = "483d8b";
        public static string Lightskyblue = "87cefa";
        public static string Lightpink = "ffb6c1";
        public static string Mediumvioletred = "c71585";
        public static string Red = "ff0000";
        public static string Deeppink = "ff1493";
        public static string Limegreen = "32cd32";
        public static string Darkmagenta = "8b008b";
        public static string Palegoldenrod = "eee8aa";
        public static string Plum = "dda0dd";
        public static string Turquoise = "40e0d0";
        public static string Lightgoldenrodyellow = "fafad2";
        public static string Darkgoldenrod = "b8860b";
        public static string Lavender = "e6e6fa";
        public static string Maroon = "800000";
        public static string Yellowgreen = "9acd32";
        public static string Sandybrown = "f4a460";
        public static string Thistle = "d8bfd8";
        public static string Violet = "ee82ee";
        public static string Navy = "000080";
        public static string Magenta = "ff00ff";
        public static string Tan = "d2b48c";
        public static string Rosybrown = "bc8f8f";
        public static string Olivedrab = "6b8e23";
        public static string Blue = "0000ff";
        public static string Lightblue = "add8e6";
        public static string Ghostwhite = "f8f8ff";
        public static string Honeydew = "f0fff0";
        public static string Cornflowerblue = "6495ed";
        public static string Linen = "faf0e6";
        public static string Darkblue = "00008b";
        public static string Powderblue = "b0e0e6";
        public static string Seagreen = "2e8b57";
        public static string Darkkhaki = "bdb76b";
        public static string Snow = "fffafa";
        public static string Sienna = "a0522d";
        public static string Mediumblue = "0000cd";
        public static string Royalblue = "4169e1";
        public static string Lightcyan = "e0ffff";
        public static string Green = "008000";
        public static string Mediumpurple = "9370db";
        public static string Midnightblue = "191970";
        public static string Cornsilk = "fff8dc";
        public static string Paleturquoise = "afeeee";
        public static string Bisque = "ffe4c4";
        public static string Slategray = "708090";
        public static string Darkcyan = "008b8b";
        public static string Khaki = "f0e68c";
        public static string Wheat = "f5deb3";
        public static string Teal = "008080";
        public static string Darkorchid = "9932cc";
        public static string Deepskyblue = "00bfff";
        public static string Salmon = "fa8072";
        public static string Darkred = "8b0000";
        public static string Steelblue = "4682b4";
        public static string Palevioletred = "db7093";
        public static string Lightslategray = "778899";
        public static string Aliceblue = "f0f8ff";
        public static string Lightgreen = "90ee90";
        public static string Orchid = "da70d6";
        public static string Gainsboro = "dcdcdc";
        public static string Mediumseagreen = "3cb371";
        public static string Lightgray = "d3d3d3";
        public static string Mediumturquoise = "48d1cc";
        public static string Lemonchiffon = "fffacd";
        public static string Cadetblue = "5f9ea0";
        public static string Lightyellow = "ffffe0";
        public static string Lavenderblush = "fff0f5";
        public static string Coral = "ff7f50";
        public static string Purple = "800080";
        public static string Aqua = "00ffff";
        public static string Whitesmoke = "f5f5f5";
        public static string Mediumslateblue = "7b68ee";
        public static string Darkorange = "ff8c00";
        public static string Mediumaquamarine = "66cdaa";
        public static string Darksalmon = "e9967a";
        public static string Beige = "f5f5dc";
        public static string Blueviolet = "8a2be2";
        public static string Azure = "f0ffff";
        public static string Lightsteelblue = "b0c4de";
        public static string Oldlace = "fdf5e6";

        public static Color ToColor(string hex)
        {
            if(!hex.StartsWith("#"))
                hex = "#" + hex;

            return ColorTranslator.FromHtml(hex);
        }
    }
}